development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: personal_test
  encoding: unicode
  pool: 25

production:
  adapter: postgresql
  database: personal_prod
  encoding: unicode
  username: jbowler2400
  password: <%= begin IO.read("/home/jbowler2400/webapps/personal/db/key.txt") rescue "" end %>
  pool: 25
