development:
  adapter: postgresql
  database: personal_dev
  encoding: unicode
  pool: 25

test:
  adapter: postgresql
  database: personal_test
  encoding: unicode
  pool: 25

production:
  adapter: postgresql
  database: personal_prod
  encoding: unicode
  pool: 25
