# Site settings
title: JT's Programming Blog
email: jbowler2400@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This blog will focus on various obstacles that come up while writing code
  and how they are solved.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jtbowler.com" # the base hostname & protocol for your site
github_username:  QuotableWater7

# Build settings
markdown: kramdown
